/options-analysis
    /models
        options_contract.go
    /handlers
        analysis_handler.go
    /utils
        calculations.go
    /tests
        options_contract_test.go
        analysis_handler_test.go
    main.go
    go.mod
